### ISSUE TITLE
Add support for error overlays?

### ISSUE THREAD

**Issue by tankorsmash** [lydell/elm-watch#29]
Hey there!

A feature I love about tools like elm-live is the ability to keep the browser and editor open at the same time, so I don't need to keep the terminal open at all.

The README was pretty clear about it being undesirable, but it was a gamechanger for me and I'd love to see something like that implemented in elm-watch.

Any chance that an optional error overlay could be enabled that would display Elm's error message in the browser?

**Comment by lydell** [comment]
I’ve added an error overlay – with clickable error locations! – and published a beta version. Please try it out and let me know what you think!

https://github.com/lydell/elm-watch/releases/tag/v1.1.0-beta.1

**Comment by tankorsmash** [comment]
Hey, this works wonderfully! Thanks for including how to update the other library in the release notes too, on top of linking to the clickable errors in the error page too.

Thank you for taking the time, it looks great!
