### ISSUE TITLE
Feature request: suport `*` in inputs file path.

### ISSUE THREAD

**Issue by STTR13** [lydell/elm-watch#38]
It would be nice to be able to use `*` characters in inputs path like so :
```elm
{
    "targets": {
        "My target name": {
            "inputs": [
                "src/App/*/Main.elm"
            ],
            "output": "build/elm.js"
        }
    }
}
```
The elm compiler does support it ;)

**Comment by lydell** [comment]
Hi!

The Elm compiler does not “support” that – your shell does. Your shell expands `elm make src/App/*/Main.elm` to for example `elm make src/App/Apple/Main.elm src/App/Banana/Main.elm src/App/Mango/Main.elm` and then executes it.

Quoting from https://github.com/lydell/elm-watch/issues/23#issuecomment-1242517212:

> I’m reluctant to adding glob support to `"inputs"` as an “easier” solution. That would require another dependency (because I’m not going to implement globs by hand), and I’m very careful with dependencies in elm-watch. Also, everything in elm-watch is designed to not be Node.js specific because I have a dream of writing elm-watch in another language one day that can compile to a standalone binary. So I would have to come up with how to “standardize” which globs are supported etc.

So I would like to hear more about your use case! What’s wrong with listing all the inputs explicitly?

**Comment by STTR13** [comment]
It is for compiling generated files
