### ISSUE TITLE
Support HTTPS with external SSL handoff

### ISSUE THREAD

**Issue by chazsconi** [lydell/elm-watch#39]
Love the project - it's really improved the productivity in our team!

However, a few weeks ago before HTTPS support was added to the project I forked the library to support our use case which is to use HTTPS, but have the SSL handoff done externally (`HAProxy` in our case). 

We have a few microservices running in our development environment under the same domain so it simplifies things that the SSL handoff is centralised.  We also use a real certificate rather than a self-signed one.

For the app we are using with `elm-watch` we have a backend server (running on port `4000`) that serves the HTML pages and then `elm-watch` backend running on port `4001`.  `HAProxy` routes `https://my-domain/*:443` to port `4000`, and `wss://my-domain/elm-watch:443`to `4001`.

My fork is hardcoded and hacky (https://github.com/lydell/elm-watch/compare/main...chazsconi:elm-watch:wss) but works.  However, I would like to do this properly and create a PR for a setup like this with some extra optional configuration parameters for `elm-watch.json` but would like some feedback first:

My idea is to have these extra parameters:

- A `ssl_handoff` field which defaults to `true`, but I would set to `false`. This would cause `elm-watch` to run the backend with `ws` (not `wss`) on the port specified by `port` regardless of if the browser is using `wss` or not.
- A `frontend_port` field which would default to the `port` field, but I would set to `443` in my case.
- A `path` field for the websocket that overrides the default `/`.  I would set this to `/elm-watch`. This would allow `HAProxy` (or similar) to route the traffic to `elm-watch` backend without having to use a different port on the frontend.  (I already tried without this and having `HAProxy` to rewrite `/elm-watch` to `/` but it seemed to confuse the browser.)

**Comment by lydell** [comment]
elm-watch (the beta version, currently) serves both HTTP and HTTPS (so, both ws and wss) on the same port. (Yes, that’s possible!)

If you have a proxy in front, can you direct it to HTTP/ws of elm-watch? Then there shouldn’t be any SSL problems, or am I missing something?

**Comment by chazsconi** [comment]
I'm now trying the latest beta and have made some progress....

So now the backend serves both HTTP and HTTPS that avoids the need to disable SSL handoff.

However, the `path` is still an issue: 

I only have access to port 443 on the front-end (in fact the setup is quite complex and a remote development environment running under Kubernetes).  I can set the `port` in `elm-watch.json` to `443` which will cause the frontend URL for the websocket to be `wss://my-domain:443/` and although the backend will also be running on `443` it will be accessed with HTTP (not HTTPS).

However to route the `elm-watch` traffic to port `443` on the backend and not `4000` (for all other traffic) all I have to differentiate is the query parameters in the websocket URL e.g. `elmWatchVersion`.  Unfortunately I can only match on paths and not on query parameters in the Kubernetes Ingress (which in fact is using NGINX not HAProxy as I wrongly stated before).

However I don't think that the websocket path needs to be configurable - if it was hardcoded on `/elm_watch` rather than `/` then that would be fine as it's easy to match on, and can't imagine if this would have a negative impact on any other users.  In fact I've tried changing the code of the beta and it all works fine with this change.  Happy to create a PR with just this change if you think this is acceptable?

**Comment by lydell** [comment]
That sounds like a very good solution! I would like the path to be `/elm-watch` with a dash and no trailing slash.

Some tips if you make a PR:

- Run the tests without changes first. Some will probably fail, because I have a problem with flakiness (#3). So don’t spend time on tests failing that seem completely unrelated to what you were changing.
- Temporarily add [.only](https://jestjs.io/docs/api#testonlyname-fn-timeout) to the tests you are working on and only run that file, for example `npx jest tests/Hot.test.ts`.
- Run Jest with the `-u` flag to update snapshots, but beware of “wrong” changes being brought in in flaky tests. Sometimes easier with find-and-replace for changes that affect many snapshots.

**Comment by chazsconi** [comment]
OK - thanks for the tips!  Will work on the PR.
