### ISSUE TITLE
Allow custom elm-watch.json location

### ISSUE THREAD

**Issue by jamesrweb** [lydell/elm-watch#44]
Thanks for the amazing package, it really is fantastic and I am using it on multiple projects now. A feature request I have is that it would be nice to be able to say something like:

```sh
npx elm-watch make --config path/to/my/elm-watch.json --optimize myTarget
```

It would also be nice if post processing done inside the `elm-watch.json` was relative to the file so that related configs like build scripts can be collocated to the `elm-watch.json` itself. Something like:

```json
{
  "postprocess": ["elm-watch-node", "build.js"],
  "targets": {
    "Main": {
      "inputs": ["../../src/Main.elm"],
      "output": "../../build/main.js"
    }
  }
}
```

In this case `build.js` would be in the same directory as the `elm-watch.json` for example.

**Comment by lydell** [comment]
Hi!

Can you provide more details? I’m very hesitant to configuration or flags so I’m I want to understand use cases very deeply and try to think of alternative solutions before implementing anything.

**Comment by jamesrweb** [comment]
Usually I have a `config` directory [like here](https://github.com/P5-wrapper/react/tree/master/config) in one of my projects. This keeps the root directory clean and most tools support custom config locations from the root, does that make sense now?

**Comment by lydell** [comment]
Yes, thank you! Thanks for the suggestion, but I’m going to pass on that one. For me, simplicity > folder cleanliness.

**Comment by jamesrweb** [comment]
I mean it is a pretty standard cli tool feature and I don't see how it makes things less simple but if that's your choice then it is what it is.
