### ISSUE TITLE
Runtime error after build with --optimize

### ISSUE THREAD

**Issue by atlewee** [lydell/elm-watch#64]
First of all, Amazing tool !
Works perfect for me in development, but tried to build a production version just now and got this error:
![image](https://github.com/lydell/elm-watch/assets/11732817/719cf75a-25cc-4a18-a755-0b58117bf989)
( Seems to be a elm-ui text input )

I am using the postprocess.js file from the example here with no modifications.
Any idea what can cause this?

Also, the editor shows an error here. (But no errors when building)
![image](https://github.com/lydell/elm-watch/assets/11732817/1f5144f5-3135-4695-b4c8-eb9afd62ebb7)

dependency versions:
![image](https://github.com/lydell/elm-watch/assets/11732817/49875feb-e0ae-4bc3-882c-f072c241a56d)

**Comment by atlewee** [comment]
Thank you for fast response!

the issue goes away if I remove this line from my elm-watch.json: 
```
"postprocess": ["elm-watch-node", "postprocess.js"],
```

So seems related to uglify or the postprocess.js file
elm-watch hot works fine, also when changing between debug/standard/optimized  
(everything works as long as that postprocess step is removed) :)

**Comment by lue-bird** [comment]
Yeah I've had encountered something similar – strangely always and only when more than one elm-ui element inside a centered element is centered.

> this is (an uglify-js bug, or) a bug in my example configuration of uglify-js

I'd say this is highly likely, especially because configurations with for example only eol2 don't break the app.

**Comment by atlewee** [comment]
aha.. The error goes away if i replace my Input.text element with (text "test")
Strange...
( I have no explicit centering going on any parents of that text input )

**Comment by lydell** [comment]
It would be amazing if you could reduce your code into a small example that reproduces the issue. Then we could dig deeper into uglify-js:

- Maybe there’s some option to it that we can toggle.
- Maybe there’s a bug we can report, or find already reported.

**Comment by atlewee** [comment]
Here is a small example that crashes:

**Main.elm**
``` elm
module Main exposing (main)

import Element exposing (..)
import Element.Input as Input


type Msg
    = NoOp


main =
    layout [] -- Converts from Element to Html
        (Input.text
            []
            { label = Input.labelHidden ""
            , onChange = always NoOp
            , placeholder = Nothing
            , text = ""
            }
        )
```

Other files for reference:

**Index.html**
``` html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>example-minimal</title>
</head>

<body>
    <div id="root"></div>
    <script src="./build/main.js"></script>
    <script>
        Elm.Main.init({ node: document.getElementById("root") });
    </script>
</body>

</html>
```

**package.json**
``` json
{
  "type": "module",
  "devDependencies": {
    "esbuild": "^0.18.0",
    "uglify-js": "^3.17.4"
  }
}
```

**elm-watch.json**
``` json
{
  "postprocess": ["elm-watch-node", "postprocess.js"],
  "targets": {
    "My target name": {
      "inputs": ["src/Main.elm"],
      "output": "build/main.js"
    }
  }
}
```

**elm.json**
``` json
{
    "type": "application",
    "source-directories": [
        "src"
    ],
    "elm-version": "0.19.1",
    "dependencies": {
        "direct": {
            "elm/browser": "1.0.2",
            "elm/core": "1.0.5",
            "elm/html": "1.0.0",
            "mdgriffith/elm-ui": "1.1.8"
        },
        "indirect": {
            "elm/json": "1.1.3",
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "elm/virtual-dom": "1.0.3"
        }
    },
    "test-dependencies": {
        "direct": {},
        "indirect": {}
    }
}
```

And the postprocess.js file is alos copied from this repo/example

**Comment by lydell** [comment]
Small update so far: By trial and error I have found that if I comment out `collapse_vars: true,` the runtime error goes away.

**Comment by lydell** [comment]
Other notes:

- I have removed elm-watch from the picture. `elm make --optimize` + uglify is enough to reproduce.
- I removed the esbuild minification to retain long names of things to make debugging easier.
- I format the output with Prettier to make debugging easier.
- Diffing with and without `collapse_vars: true`:

```diff
     $mdgriffith$elm_ui$Element$Input$hasFocusStyle = function (attr) {
-      return attr.b.a, 4 === attr.$ && 11 === attr.b.$ && !attr.b.a && true;
+      return (
+        4 === attr.$ &&
+        11 === attr.b.$ &&
+        !attr.b.a &&
+        ((attr = attr.b), attr.a, true)
+      );
     },
```

That transformation is wrong. Currently trying to reduce the compiled JS to make a small example that can be reported to uglify (or searched for in their issue tracker).

**Comment by lydell** [comment]
New finding: _Adding_ `side_effects: true,` also makes the runtime error go away. (I haven’t measured how it affects speed and size yet.)

**Comment by lydell** [comment]
I managed to make a bug report for uglify: https://github.com/mishoo/UglifyJS/issues/5794

**Comment by lydell** [comment]
I replaced uglify with SWC in https://github.com/lydell/elm-watch/commit/951ad3c79582ed960a6c571f02b1988bc41892de

It’s faster, simpler and minifies about the same: https://discourse.elm-lang.org/t/elm-minification-benchmarks/9968
