### ISSUE TITLE
Allow building a file with the hot-reload code inserted

### ISSUE THREAD

**Issue by peacememories** [lydell/elm-watch#69]
Hi, and thanks for the great work you're doing on elm-watch. We're using it happily in our Django application at work. There are a few features that would make life much easier for us, especially as we would like to integrate our build more directly into Django.

Together with #68, it would be very useful for us to be able to `elm-watch make` a js file, but still insert the hot-reload code.
The way I would imagine this working is that we could, on a request to our website, generate the js file as a oneshot, which would have the hot-reload code attached so **if** a developer has `elm-watch hot` running, the hot-reload connects and they can develop efficiently.

**Comment by lydell** [comment]
See the discussion in https://github.com/lydell/elm-watch/issues/68
