### ISSUE TITLE
Add output to postprocess arguments

### ISSUE THREAD

**Issue by harmboschloo** [lydell/elm-watch#90]
I'm migrating from webpack to elm-watch at work.

At the moment in postprocess I"m extracting some css information from the elm code and writing that to a file next to the elm output file. But since the output path is not available in postprocess I'm currently reading the `elm-watch.json` and looking up the output path through the `targetName`. This feels very clunky, but works 😅.

Could the output path of the code be added to the postprocess arguments? That would help a lot with our setup.

I've tried/considered other setups for extracting the css information, but at the moment doing it in postprocess seems to be the best approach for us.

**Comment by lydell** [comment]
I’m closing this for now. Feel free to post more if you have something more to say and we might reopen!
